Refactor clipping mask rendering
maplibre/maplibre-native pull request #1209
Opened 2023-06-05 22:27 UTC by TimSylvester

`renderTileClippingMasks` only uses the tile ID out of `RenderTiles`, so I refactored it to work on generic sets of tile IDs and called it with the tile IDs of stencil-requiring drawables from the layer.  That should be equivalent to the call that the `RenderLayer` would have done.

I see the values being rendered with `GL_ALWAYS` and used with `GL_EQUAL` in the frame capture, so I think it's working, but it's hard to tell.

2023-06-05 22:30 UTC, TimSylvester commented on src/mbgl/renderer/paint_parameters.cpp
> +    if (nextStencilID + count > 256) {
I suspect this should be `>255`.  The `mask` value passed to `glStencilFunc` is 255, so I don't see how a value of 256 could work, unless it's meant to be equivalent to 0.

2023-06-06 03:11 UTC, sjg-wdw approved these changes
That... actually made some sense.

2023-06-06 11:44 UTC, alexcristici approved these changes

2023-06-06 15:28 UTC, mwilsnd requested changes

2023-06-06 16:57 UTC, TimSylvester commented on src/mbgl/renderer/paint_parameters.cpp
> +                      std::function<const UnwrappedTileID&(typename TIter::value_type)> f,
Which instantiation?  Neither seems like it should be creating a temporary.

2023-06-06 18:05 UTC, mwilsnd commented on src/mbgl/renderer/paint_parameters.cpp
> +                      std::function<const UnwrappedTileID&(typename TIter::value_type)> f,
Yeah I'm only seeing this in MSVC, guessing it's seeing through copy elision/NRVO It's still happening unless I comment out every call to `renderTileClippingMasks` or comment out the check inside that invokes `tileIDsIdentical`.

2023-06-06 19:35 UTC, mwilsnd approved these changes

2023-06-06 21:15 UTC, merged