Android Annotations proposal
maplibre/maplibre-native pull request #1255
Opened 2023-06-18 21:15 UTC by fynngodau

Fixes #1189 by planning a new and improved annotations API for Android.

Latest version for reading: https://github.com/fynngodau/maplibre-native/blob/annotations-proposal/design-proposals/2023-06-17-android-annotations.md

2023-06-21 19:41 UTC, RomanBapst commented
@fynngodau Thanks for bringing up this proposal! I went through it today and liked the direction it takes a lot.
Actually it's quite funny because me and @JonasVautherin released [ramani-maps](https://github.com/ramani-maps/ramani-maps) today and many things you have in the proposal are quite similar to what we have done. E.g. managing the layering under the hood and just exposing a zIndex to the user is exactly what we have done. Also the fact that you propose to instantiate the annotation classes directly is pretty much what we do in compose. With compose we have the additional advantage that it's super declarative, e.g. you add a Circle directly to the UI code.

From what I understand the old workflow of adding annotations via the manager would still co-exists, right? That's important for us in our library as we currently make use of it.

What I like a lot are all the options that can be used to fine-tune the appearance of the elements, e.g. Padding, Transform, ...
And of course I am excited to see the as much "Kotlinification" as possible.

2023-06-22 04:22 UTC, fynngodau commented
@RomanBapst Your library sounds very exciting!

> From what I understand the old workflow of adding annotations via the manager would still co-exists, right? That's important for us in our library as we currently make use of it.

Yes, this is what I had in mind. It wouls be necessary to create annotations using the changed API, but they could still be added to annotation managers as previously. As explained in the proposal, the two use main cases are

* when you really can't affort the matching algorithm to take O(n log n) (and have additional knowledge about the desired z layers in advance)
* when you want to call methods that are not available on the specific Annotation

2023-06-26 11:51 UTC, systemed commented
As a general note, while porting cycle.travel's app from iOS to Android, I've been surprised how different the Android and iOS APIs are.

Obviously each platform has its own design patterns (e.g. iOS delegates, Android builders, etc.) so you wouldn't expect full convergence, but there's a lot that seems needlessly different between the two - annotations being just one example. It means a whole bunch of extra cognitive load when porting or developing in parallel. From looking through issues on the old Mapbox repos it looks like their two teams were working independently.

So perhaps an additional design goal would be appropriate: increased commonality with MapLibre iOS Native. That doesn't necessarily imply changes have to be made here in Androidland - it could equally mean changing the iOS API to match the new, better Android API. But I think it's worth considering as an aim.

2023-06-26 17:28 UTC, louwers commented
@systemed Very interesting point! Now that Swift is the language of choice for iOS development, I think it makes sense to offer a Swift-first API in the future. Being a much more modern programming language with quite powerful features (in comparison to Objective-C), I think a lot is possible there. If you have specific ideas in mind or want to contribute, check out the general topic for iOS modernization #1248.

I gave you a follow in LinkedIn, let me know if you ever want to brainstorm about this.

2023-06-28 09:45 UTC, systemed commented
Cheers!

Swift and Kotlin are broadly similar languages, each with a good async/await story and heavy use of blocks/closures. To my mind this gives the opportunity to remove some of the more idiomatic design patterns (Java-ish managers and builders, ObjC-ish delegates) and converge on a simpler, more direct API. So @fynngodau's suggestion of de-emphasising manager objects makes a lot of sense in this context.

2023-07-02 13:56 UTC, louwers requested changes

2023-07-02 13:57 UTC, louwers commented on design-proposals/2023-06-17-android-annotations.md
> +`maplibre-native` contains a deprecated variant of annotation methods that work with objects such as `Marker`, `Polygon` and more that imitate the Google Maps API. On the other hand, `maplibre-plugin
```suggestion
MapLibre Native contains a deprecated variant of annotation methods that work with objects such as `Marker`, `Polygon` and more that imitate the Google Maps API. On the other hand, `maplibre-plugins-android` repository contains an implementation that works with the objects `Symbol`, `Fill` and more. This situation is confusing to developers and users and should be cleaned up.
```

2023-07-02 13:59 UTC, louwers approved these changes
Disregard my earlier comment, I think it is better to use `maplibre-native` since you are referring to the repo, not the project.

LGTM!

2023-07-02 20:58 UTC, merged