Topic/tweaker refactor
maplibre/maplibre-native pull request #1299
Opened 2023-06-30 18:29 UTC by TimSylvester

Replace lambdas with drawable tweakers

2023-06-30 19:06 UTC, sjg-wdw approved these changes
Much better.  Thanks!

2023-06-30 19:22 UTC, mwilsnd requested changes

2023-06-30 19:22 UTC, mwilsnd commented on src/mbgl/gfx/drawable_tweaker.cpp
> +
What's this for?

2023-06-30 23:39 UTC, TimSylvester commented on src/mbgl/gfx/drawable_tweaker.cpp
> +
Probably not needed, I can remove it.

2023-07-01 00:22 UTC, mwilsnd approved these changes

2023-07-03 09:03 UTC, stefankarschti approved these changes

2023-07-03 11:08 UTC, alexcristici approved these changes

2023-07-03 14:40 UTC, merged