shared vertex buffers
maplibre/maplibre-native pull request #1310
Opened 2023-07-04 18:04 UTC by TimSylvester

I was able to convert symbol bucket data to a `shared_ptr` and pass it through the `VertexAttribute` without too much trouble.  It ended up being more changes that I expected, but I also found and fixed some bugs along the way.

Currently just a proof-of-concept applied to a single attribute.  Any thoughts on the approach?

2023-07-05 19:32 UTC, mwilsnd requested changes
Looking promising - can you rebase or merge in the latest from topic/drawable?

2023-07-05 19:32 UTC, mwilsnd commented on src/mbgl/gfx/vertex_vector.hpp
> +struct VertexVectorBase {
This should ether be a class type or the forward decl in `vertex_attribute.hpp` needs to change to struct

2023-07-05 19:32 UTC, mwilsnd commented on src/mbgl/gl/upload_pass.cpp
> +                /*.attribute = */ {effectiveAttr.getSharedType(), effectiveAttr.getSharedOffset()},
`getSharedOffset` and `getSharedVertexOffset` should return `uint32_t` or a static_cast should be done here. (narrowing conversion warning, MSVC C4838).

2023-07-05 20:02 UTC, sjg-wdw approved these changes
Seems like a move in the right direction for sharing those resources.

2023-07-06 23:24 UTC, mwilsnd reviewed
This is good improvement. We're down to around 40% more memory vs. the legacy renderer.

Legacy: RAM 212,576K, VRAM 207,888K
![image](https://github.com/maplibre/maplibre-native/assets/53413200/15a3c408-9c9b-47cc-a6a8-ba4031d266fc)

Drawable: RAM 414,884, VRAM 313,968K
![image](https://github.com/maplibre/maplibre-native/assets/53413200/0d474a1b-3e27-41bb-8411-a47b2d846f90)

Looks like there is an artifact around the edges of fill patterns:
![image](https://github.com/maplibre/maplibre-native/assets/53413200/2c05f4e9-661b-43ad-b409-f876a49e7697)

2023-07-07 00:18 UTC, mwilsnd commented
The artifact was introduced in #1288

2023-07-07 09:53 UTC, stefankarschti approved these changes

2023-07-07 14:13 UTC, TimSylvester commented on src/mbgl/gfx/drawable_builder.cpp
> +        if (auto drawAttrs = builderAttrs.clone()) {
Yeah, the drawables and builders could take shared references to attributes and that would be a good next step.
That's a bit problematic when the builder is setting up the attributes and might be modifying something that's being shared, but the direction we're going it's less so.

2023-07-07 15:03 UTC, sjg-wdw commented on src/mbgl/gfx/drawable_builder.cpp
> +        if (auto drawAttrs = builderAttrs.clone()) {
There are two use cases for the Builders now I think.  One is the flexible one that we envisioned originally and the other is this sort of reference and rework mode that we're using with the buckets.
We could go as far as making that explicit when setting them up.  If you're in that more strict memory mode then you don't allow the developer to add new geometry to a builder, perhaps.

2023-07-07 18:33 UTC, mwilsnd approved these changes

2023-07-07 21:52 UTC, alexcristici approved these changes

2023-07-07 22:03 UTC, merged