Custom layer
maplibre/maplibre-native pull request #1312
Opened 2023-07-04 20:20 UTC by stefankarschti

#1272 
First version. Entanglement to GL is quite high, still. Marked TODOs to discuss options.

2023-07-04 20:30 UTC, stefankarschti commented on src/mbgl/gfx/drawable_custom_layer_host_tweaker.cpp
> +    paintParameters.backend.getDefaultRenderable().getResource<gl::RenderableResource>().bind();
this is still entangled to GL unless we push it to Context.

2023-07-04 20:31 UTC, louwers commented
We have an example (legacy) custom layer here: https://github.com/maplibre/maplibre-native/blob/topic/drawable/platform/android/src/example_custom_layer.cpp

Would be good to have something similar for the drawable-based custom layer when the design is finalized.

2023-07-04 20:32 UTC, stefankarschti commented on src/mbgl/gfx/context.hpp
> +    virtual void setDirtyState() = 0;
this was GL specific.

2023-07-05 18:57 UTC, stefankarschti commented
> We have an example (legacy) custom layer here: https://github.com/maplibre/maplibre-native/blob/topic/drawable/platform/android/src/example_custom_layer.cpp
> 
> Would be good to have something similar for the drawable-based custom layer when the design is finalized.

At this stage there should be no disruption, so the existing `CustomLayerHost` interface will continue to work.
As this is now internally untangled from GL, the same interface could be used with different backends, once they are implemented.

2023-07-05 19:50 UTC, sjg-wdw commented
We'd need to add more data to what's currently passed in to make this a generic custom layer.
I also think we'll want more methods to call in different places.  But let's revisit next phase.

2023-07-05 19:55 UTC, sjg-wdw approved these changes
This looks like a good way to do it for now.
For the next version I can see we'll want a bunch of callbacks in various place.
preRender/postRender,update, that sort of thing.

2023-07-05 20:31 UTC, mwilsnd requested changes
Looks like there is still more work to get the custom layer wired up, as is  `./build/mbgl-test-runner --gtest_filter=CustomLayer.Basic` fails because `RenderCustomLayer::update` never gets called. The general approach here looks pretty good though.

2023-07-06 17:41 UTC, stefankarschti commented
> Looks like there is still more work to get the custom layer wired up, as is `./build/mbgl-test-runner --gtest_filter=CustomLayer.Basic` fails because `RenderCustomLayer::update` never gets called. The general approach here looks pretty good though.

[This condition](https://github.com/maplibre/maplibre-native/blob/c02099e23f325101d1724ec0c89be3bd38de502e/src/mbgl/renderer/renderer.cpp#L40C13-L40C58) is never true during the test run. No layers

2023-07-06 17:46 UTC, mwilsnd commented
> > Looks like there is still more work to get the custom layer wired up, as is `./build/mbgl-test-runner --gtest_filter=CustomLayer.Basic` fails because `RenderCustomLayer::update` never gets called. The general approach here looks pretty good though.
> 
> [This condition](https://github.com/maplibre/maplibre-native/blob/c02099e23f325101d1724ec0c89be3bd38de502e/src/mbgl/renderer/renderer.cpp#L40C13-L40C58) is never true during the test run. No layers will be updated with a `HeadlessFrontend` Ideas?

Ah, that would do it! `impl->render` will check for and create `staticData` if it doesn't exist, but we want update to run, so we need to make sure staticData is created before that point.

Why not add a `preRender` method to `Renderer::Impl`, then we can move the staticData creation check from `render` to `preRender` and call `preRender` before that check.

2023-07-06 18:10 UTC, stefankarschti commented
> > > Looks like there is still more work to get the custom layer wired up, as is `./build/mbgl-test-runner --gtest_filter=CustomLayer.Basic` fails because `RenderCustomLayer::update` never gets called. The general approach here looks pretty good though.
> > 
> > 
> > [This condition](https://github.com/maplibre/maplibre-native/blob/c02099e23f325101d1724ec0c89be3bd38de502e/src/mbgl/renderer/renderer.cpp#L40C13-L40C58) is never true during the test run. No layers will be updated with a `HeadlessFrontend` Ideas?
> 
> Ah, that would do it! `impl->render` will check for and create `staticData` if it doesn't exist, but we want update to run, so we need to make sure staticData is created before that point.
> 
> Why not add a `preRender` method to `Renderer::Impl`, then we can move the staticData creation check from `render` to `preRender` and call `preRender` before that check.

Shaders get created after (`backend.getDefaultRenderable().wait();`)[https://github.com/maplibre/maplibre-native/blob/c02099e23f325101d1724ec0c89be3bd38de502e/src/mbgl/renderer/renderer_impl.cpp#L75] in `Renderer::Impl::render`, so that needs to tag along to `preRender` I suppose.

2023-07-07 00:47 UTC, mwilsnd approved these changes

2023-07-07 18:10 UTC, alexcristici approved these changes

2023-07-07 18:24 UTC, merged