Update minimum CMake version to 3.19
maplibre/maplibre-native pull request #1643
Opened 2023-09-17 09:38 UTC by ntadej

Update minimum CMake version to 3.19. Will need a separate PR to update to a container that is containing this CMake version but the one we have now should do it by then.

/cc @alanchenboy

2023-09-17 09:46 UTC, louwers requested changes
Looks like the Node.js workflow also needs to be updated.

2023-09-17 09:51 UTC, ntadej commented
> Looks like the Node.js workflow also needs to be updated.

Added a setup-cmake acction, but not sure if it will work on a self-hosted runner. Let's see.

2023-09-17 11:51 UTC, louwers commented
@ntadej Looks like it is not platform aware (self-hosted runner uses ARM64).

2023-09-23 18:35 UTC, ntadej commented on .github/actions/qt5-build/Dockerfile
> +FROM ghcr.io/maplibre/linux-builder:centos7-latest
```suggestion
FROM ghcr.io/maplibre/linux-builder:centos7-cmake3.19
```

2023-10-03 07:48 UTC, alanchenboy commented
Thanks for this updating

2023-10-07 11:39 UTC, ntadej commented
@louwers, I think we need to just figure out how to update CMake in the Linux ARM runner? Can you just do it system-wide maybe?

2023-10-07 17:38 UTC, louwers commented
@ntadej Thanks for the heads up. Yes, I can do that.

2023-10-09 10:35 UTC, louwers approved these changes

2023-10-09 10:35 UTC, merged