[qt] Make WASM build run without crashes with latest Qt
maplibre/maplibre-native pull request #1709
Opened 2023-09-30 15:08 UTC by ntadej

Make WASM build run without crashes with latest Qt (6.5.3). The "screen" is still black but there are no errors in the console.

To build:
- Setup Emscripten 3.1.25
- Setup Qt 6.5.3 with WASM (multithreaded) support
- Run
```
qt-cmake ../../maplibre-gl-native \
-G Ninja \
-DCMAKE_BUILD_TYPE="RelWithDebInfo" \
-DMLN_WITH_QT=ON \
-DMLN_QT_STATIC=ON \
-DMLN_QT_WITH_INTERNAL_SQLITE=ON
```

/cc @louwers @birkskyum

2023-09-30 15:12 UTC, birkskyum commented
Do you think it's necessary to add Asyncify as a linker flag? They write:

> As of Qt 6.4, Asyncify support is enabled in the binary package, but needs to be enabled for applications by adding -sASYNCIFY -Os to linker options:

And I'm not sure how to interpret it.

2023-09-30 15:16 UTC, ntadej commented
> Do you think it's necessary to add Asyncify as a linker flag? They write:
> 
> > As of Qt 6.4, Asyncify support is enabled in the binary package, but needs to be enabled for applications by adding -sASYNCIFY -Os to linker options:
> 
> And I'm not sure how to interpret it. Are we having a binary package or an application in this context?

I have no idea what Asyncify is 😊 According to Google this is for browser-app communication so this will not solve the black screen.

2023-09-30 15:30 UTC, ntadej commented
Hmm, will investigate the CMake issue, we may need the CMake version bump first.

2023-09-30 15:44 UTC, birkskyum commented
I experienced something similar with incorrect args when i didn't have an exact match of these:

Qt 6.2 = Emcsripten 2.0.14
Qt 6.3 = Emcsripten 3.0.0
Qt 6.4 = Emcsripten 3.1.14
Qt 6.5 = Emcsripten 3.1.25

2023-09-30 15:47 UTC, birkskyum commented
Asyncify will be needed for any async tasks, like async http requests and file i/o - So we'll probably be needing it.

2023-09-30 15:50 UTC, ntadej commented
> afaik Asyncify is needed for any async tasks in wasm, like async http requests and file i/o - So we'll probably be needing it.

Do you know if this is only for apps or do we need it already for static libraries? At what stage does the actual "web glue" happen?

2023-09-30 17:51 UTC, birkskyum commented
I should be in the static library. Module["Asynchify"] should be possible to check in the html if the function is exported doing linking.

2023-10-01 21:38 UTC, birkskyum approved these changes
I was able to checkout this PR, source emsdk, make a build and run it without modifying a single line in the repo, so if only the CI would pass.

2023-10-01 22:37 UTC, louwers commented on platform/qt/qt.cmake
>          ${PROJECT_SOURCE_DIR}/platform/qt/app/main.cpp
I think you have to store these in a list and then pass them to `add_executable` / `qt_add_executable`/

2023-10-01 22:37 UTC, louwers commented
Thanks for reviewing @birkskyum

2023-10-04 09:16 UTC, birkskyum commented
Related to:
- https://github.com/maplibre/maplibre-native/issues/454

2023-10-07 09:41 UTC, birkskyum commented
@ntadej , do you have any ideas how the tests can be fixed?

2023-10-07 19:52 UTC, birkskyum commented
It's data loading that is missing.

The http requests doesn't appear to work correctly, so the canvas is black because the style, and ofc. tiles, are never loaded.

2023-10-10 18:29 UTC, birkskyum commented
Are the changes to all the vendor .cmake files intended to be part of this PR?

2023-10-10 18:31 UTC, ntadej commented
> Are the changes to all the vendor .cmake files intended to be part of this PR?

Yes, the `sqlite` one is needed, the rest I just unified. It's not directly related to WASM, but it is to Qt.

2023-10-10 18:33 UTC, ntadej commented
Yes, I pushed to `qt-wasm-experimental` if you want to play with it (it's based on `opengl-2` branch).

2023-10-10 18:34 UTC, birkskyum commented
With the latest version of this PR I can't ninja compile it anymore. I get:

```sh
em++: warning: -pthread + ALLOW_MEMORY_GROWTH may run non-wasm code slowly, see https://github.com/WebAssembly/design/issues/1271 [-Wpthreads-mem-growth]
wasm-ld: error: libQMapLibreGL.a(sqlite3.cpp.o): undefined symbol: sqlite3_open_v2
wasm-ld: error: libQMapLibreGL.a(sqlite3.cpp.o): undefined symbol: sqlite3_errmsg
wasm-ld: error: libQMapLibreGL.a(sqlite3.cpp.o): undefined symbol: sqlite3_close
wasm-ld: error: libQMapLibreGL.a(sqlite3.cpp.o): undefined symbol: sqlite3_extended_result_codes
wasm-ld: error: libQMapLibreGL.a(sqlite3.cpp.o): undefined symbol: sqlite3_errmsg
wasm-ld: error: libQMapLibreGL.a(sqlite3.cpp.o): undefined symbol: sqlite3_close
wasm-ld: error: libQMapLibreGL.a(sqlite3.cpp.o): undefined symbol: sqlite3_errmsg
wasm-ld: error: libQMapLibreGL.a(sqlite3.cpp.o): undefined symbol: sqlite3_close
wasm-ld: error: libQMapLibreGL.a(sqlite3.cpp.o): undefined symbol: sqlite3_errmsg
wasm-ld: error: libQMapLibreGL.a(sqlite3.cpp.o): undefined symbol: sqlite3_busy_timeout
wasm-ld: error: libQMapLibreGL.a(sqlite3.cpp.o): undefined symbol: sqlite3_errmsg
wasm-ld: error: libQMapLibreGL.a(sqlite3.cpp.o): undefined symbol: sqlite3_exec
wasm-ld: error: libQMapLibreGL.a(sqlite3.cpp.o): undefined symbol: sqlite3_free
wasm-ld: error: libQMapLibreGL.a(sqlite3.cpp.o): undefined symbol: sqlite3_errmsg
wasm-ld: error: libQMapLibreGL.a(sqlite3.cpp.o): undefined symbol: sqlite3_prepare_v2
wasm-ld: error: libQMapLibreGL.a(sqlite3.cpp.o): undefined symbol: sqlite3_errmsg
wasm-ld: error: libQMapLibreGL.a(sqlite3.cpp.o): undefined symbol: sqlite3_finalize
wasm-ld: error: libQMapLibreGL.a(sqlite3.cpp.o): undefined symbol: sqlite3_reset
wasm-ld: error: libQMapLibreGL.a(sqlite3.cpp.o): undefined symbol: sqlite3_clear_bindings
wasm-ld: error: libQMapLibreGL.a(sqlite3.cpp.o): undefined symbol: sqlite3_reset
wasm-ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
em++: error: '/Users/admin/repos/emsdk/upstream/bin/wasm-ld -o mbgl-qt.wasm /Users/admin/Qt/6.6.0/wasm_multithread/plugins/imageformats/objects-Release/QGifPlugin_init/QGifPlugin_init.cpp.o 
```

2023-10-10 18:35 UTC, ntadej commented
Ah, I mainly develop now with standalone `maplibre-native-qt` in mind. Let me fix it for now also here.

2023-10-10 18:42 UTC, birkskyum commented
I still get the same error.

2023-10-10 18:44 UTC, ntadej commented
OK, let me try something else.

2023-10-12 01:07 UTC, birkskyum requested changes
qt-ci fails on linux

2023-10-13 01:02 UTC, birkskyum commented
I managed to get cmake working by changing line 285-286 in qt.cmake from:

        $<BOOL:${MLN_QT_WITH_INTERNAL_SQLITE}>,$<BUILD_INTERFACE:mbgl-vendor-sqlite>>
        $<$<AND:<$<PLATFORM_ID:Linux>,$<BOOL:${MLN_QT_WITH_INTERNAL_ICU}>>,$<BUILD_INTERFACE:mbgl-vendor-icu>>

to

        $<$<BOOL:${MLN_QT_WITH_INTERNAL_SQLITE}>:$<BUILD_INTERFACE:mbgl-vendor-sqlite>>
        $<$<AND:$<PLATFORM_ID:Linux>,$<BOOL:${MLN_QT_WITH_INTERNAL_ICU}>>:$<BUILD_INTERFACE:mbgl-vendor-icu>>

but ninja now gives me errors related to libnu not being found:

```sh
/Users/admin/repos/maplibre-native/platform/default/src/mbgl/i18n/collator.cpp:1:10: fatal error: 'libnu/strcoll.h' file not found
#include <libnu/strcoll.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
```

2023-10-14 10:51 UTC, birkskyum approved these changes

2023-10-14 12:01 UTC, birkskyum commented
I tried applying the changes from `qt-wasm-experimental` on top of this, but the canvas stayed black. Opening the browser console prints this non-browser terminal the message below. Could be due to opengl v3, so maybe a linux box would give different result.

```sh
127.0.0.1 - - [14/Oct/2023 13:50:14] code 404, message File not found: /Users/admin/repos/build/mbgl-qt.wasm.dwp
127.0.0.1 - - [14/Oct/2023 13:50:14] "GET /mbgl-qt.wasm.dwp HTTP/1.1" 404 -
```

2023-10-14 12:20 UTC, merged