implement fill extrusion pattern shader for metal
maplibre/maplibre-native pull request #1729
Opened 2023-10-04 09:50 UTC by alanchenboy

implement fill extrusion pattern shader for metal

verify code:

```
CGRect rect = CGRectMake(0, 0, 64, 64);
    CGRect rect2 = CGRectMake(0, 0, 32, 32);
    UIColor *redColor = [UIColor redColor] ;
    UIGraphicsBeginImageContext(rect.size);
    [redColor setFill];
    UIRectFill(rect);
    [UIColor.blueColor setFill];
    UIRectFill(rect2);
    UIImage *patternImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    [style setImage:patternImage forName:@"testImage"];

    
    CLLocationCoordinate2D triangleCoordinates[] =
    {
        CLLocationCoordinate2DMake(0, 0),
        CLLocationCoordinate2DMake(0, 0.0001),
        CLLocationCoordinate2DMake(0.0001, 0.0001),
        CLLocationCoordinate2DMake(0.0001, 0),
        CLLocationCoordinate2DMake(0, 0),
    };

    MLNPolygon *triangle = [MLNPolygon polygonWithCoordinates:triangleCoordinates count:5];
    
    MLNShapeSource *source = [[MLNShapeSource alloc] initWithIdentifier:@"source" shape:triangle options:nil];
    
    MLNFillExtrusionStyleLayer *layer = [[MLNFillExtrusionStyleLayer alloc] initWithIdentifier:@"layer" source:source];
    
    
    layer.fillExtrusionHeight = [NSExpression expressionForConstantValue:@20];
    layer.fillExtrusionColor = [NSExpression expressionForConstantValue:UIColor.redColor];
    layer.fillExtrusionPattern = [NSExpression expressionForConstantValue:@"testImage"];

    [style addSource:source];
    [style addLayer:layer];
    
    
    mapView.pitchEnabled = true;
    
    mapView.camera = [MLNMapCamera cameraLookingAtCenterCoordinate:CLLocationCoordinate2DMake(0, 0) altitude:100 pitch:45 heading:45];
```

![Simulator Screen Shot - iPhone 14 Plus - 2023-10-04 at 17 33 59](https://github.com/maplibre/maplibre-native/assets/5135389/29e43a06-228e-4365-967e-605f1ee21c7a)

2023-10-05 12:42 UTC, stefankarschti approved these changes

2023-10-05 13:03 UTC, louwers requested changes
Very cool! Could you merge in `main`?

We merged in some changes yesterday and today that get rid of the `MLN_MTL_UNIFORM_BLOCK`macro

2023-10-05 14:02 UTC, TimSylvester approved these changes
Needs to be updated to the new static approach, but otherwise looks good, thanks!

2023-10-07 03:21 UTC, alanchenboy commented
MLN_MTL_UNIFORM_BLOCK was removed and moved to the new static approach. Please take a new look, thanks.

2023-10-07 18:28 UTC, louwers approved these changes

2023-10-08 02:13 UTC, merged