[ci] Cleanup caches in the target repo
maplibre/maplibre-native pull request #1758
Opened 2023-10-14 23:34 UTC by ntadej

We need to use `pull_request_target` so that caches from forks are deleted. We only request relevant permissions so this should be safe enough.

Also quote variables, just in case.

Why delete caches? We cache a lot of data and the quota we have is low. This prevents relevant caches to get evicted too soon.

2023-10-14 23:35 UTC, ntadej commented
We may want to clear all caches once this is merged. I can do that if fine with you @louwers.

2023-10-15 18:17 UTC, louwers requested changes
The Qt workflows are using up 4260MB of cache storage for a single workflow run, almost half of the 10GB cache limit. So even if this is merged relevant caches probably evicted too soon.

<img width="865" alt="image" src="https://github.com/maplibre/maplibre-native/assets/649392/6327620d-d49b-48e9-bb0a-6ff07f07caec">

Let's solve that problem first... One idea is to use an S3 Cache:

https://github.com/marketplace/actions/s3-cache-for-github-actions

We would save only on main (because a secret is needed) but retrieve with a public read-only key.

I'm not sure if I like removing caches from PRs because when workflows get skipped on `main` (ideally almost always when a workflow already ran for a PR with the same code) we'd potentially end up with a stale cache.

2023-10-15 18:21 UTC, ntadej commented
Yes, I will disable the debug symbols.

Still now all PR caches stay there. I see no reason why this would not get merged. It will never affect the caches of the branch merged into.

2023-10-15 18:41 UTC, ntadej commented
To add, we already evict caches for PRs open from branches directly in this repo. It's just the forks that do not work.

2023-10-16 12:52 UTC, louwers commented
>  It will never affect the caches of the branch merged into.

If a PR adds a node module (as an example), it will create a cache for it, then when it is merged the workflow is skipped on main and the cache is deleted. A subsequent PR won't have a cache of the node modules.

We can still merge this but we should not check out any code in a `pull_request_target` workflow.

2023-10-16 12:59 UTC, ntadej commented
PRs only use caches from `main` or their own caches. `main` will always recreate caches (I guess to avoid getting some malicious data from PRs). At least this is my experience.

AFAIK we need the clone for GitHub CLI to work, but I can try to workaround it. Also I see no security issue in cloning what was just merged in `main` because this runs after merge so as long nothing malicious is merged, we are fine.

Regarding `ccache` size, I think we accumulate historic data each time the code changes. We need to set some sensible limit e.g. 200 MB (or maybe even lower). I will look into it.

2023-10-16 15:02 UTC, ntadej commented
Sure, and then we should also delete the caches as they are irrelevant. As far as I understand this will still take the action from the `main` branch so we should not have a problem (but we can test it).

2023-10-16 15:22 UTC, louwers approved these changes

2023-10-16 15:28 UTC, ntadej commented
Hmm, nothing happened. I guess this is good from security point of view, although not solving the caches issues 😊

Let's merge this for now and monitor the behaviour.

2023-10-16 16:57 UTC, merged