Custom drawable Symbol
maplibre/maplibre-native pull request #1908
Opened 2023-12-01 15:38 UTC by stefankarschti

ref #1904

2024-01-10 17:23 UTC, louwers requested changes
Can you add a test?

Maybe something that outputs that piece of art?

2024-01-22 16:08 UTC, mwilsnd approved these changes
Looking really good! In a follow up PR, can you add a test that renders an icon across a tile boundary?

2024-01-23 14:07 UTC, stefankarschti commented
> Looking really good! In a follow up PR, can you add a test that renders an icon across a tile boundary?

Of course. I'm looking at the current implementation, which anchors the symbol at `(0.5, 0.5)` of tile `(11, 327, 791)` and trying out various scenarios:
`scaleWithMap=true`, `pitchWithMap=false`
![image](https://github.com/maplibre/maplibre-native/assets/4198736/02851cc4-3633-41a8-953a-7d3e804c3a45)

`scaleWithMap=false`, `pitchWithMap=false`
![image](https://github.com/maplibre/maplibre-native/assets/4198736/d1239eb0-da55-48fe-8401-d6a84b648f45)

`scaleWithMap=false`, `pitchWithMap=true`
![image](https://github.com/maplibre/maplibre-native/assets/4198736/8f715d13-ff7d-49b7-aff1-847a78124ddd)

`scaleWithMap=true`, `pitchWithMap=true`
![image](https://github.com/maplibre/maplibre-native/assets/4198736/e60afea7-fab3-4c26-87b0-1ffb56249c2d)

2024-01-23 14:18 UTC, mwilsnd commented
Great, that covers my curiosity.

2024-01-23 15:26 UTC, TimSylvester approved these changes

2024-01-30 20:29 UTC, alexcristici commented on src/mbgl/style/layers/custom_drawable_layer.cpp
> +        static const StringIdentity idDrawableUBOName = stringIndexer().get("CustomSymbolIconDrawableUBO");
You will have to update the UBO definition, after https://github.com/maplibre/maplibre-native/pull/1980 will be merged.

2024-02-15 19:30 UTC, alexcristici commented on src/mbgl/style/layers/custom_drawable_layer.cpp
> +            builder->setTexture(symbolOptions.texture, *textureLocation);
I just merged https://github.com/maplibre/maplibre-native/pull/2107, so you probably need to update this code in order to compile.

2024-02-16 15:25 UTC, louwers approved these changes
Awesome!

2024-02-16 15:39 UTC, merged