Synchronous rendering on Metal when annotation views are visible
maplibre/maplibre-native pull request #2334
Opened 2024-04-25 17:08 UTC by stefankarschti

Implement conditional synchronous rendering on Metal backend when annotation views are visible, that is waiting for frames to fully complete by invoking `[commandBuffer waitUntilCompleted];` in the `swap` method of the `MLNMapViewMetalRenderableResource`.

This is needed because the map transformation is set as soon as the camera is mutated, and annotations are positioned on the screen according to that in `MLNMapView`::`renderSync` -> `updateAnnotationViews`, while the frame rendering is completing asynchronously on Metal - which causes desynchronization.

Fixes #2053

2024-04-29 14:41 UTC, mwilsnd requested changes

2024-04-29 14:41 UTC, mwilsnd commented on platform/ios/src/MLNMapView+Metal.h
> +    virtual void setSynchronous(bool value) override { synchronousFrame = value; };
nit: `virtual` isn't required when the `override` keyword is present, high compiler warning levels can complain if they follow the core guidelines on [virtual, override and final](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines.html#c128-virtual-functions-should-specify-exactly-one-of-virtual-override-or-final)

2024-04-29 16:18 UTC, mwilsnd approved these changes

2024-04-29 19:08 UTC, merged

2024-05-09 02:36 UTC, michaelkirk commented
Thank you so much, it looks much better now! ❤️