Fix qt wasm webgl1 compilation
maplibre/maplibre-native pull request #2689
Opened 2024-08-05 22:50 UTC by birkskyum

This fixes these changes with compile flags:

https://github.com/birkskyum/maplibre-native-wasm/tree/main/qt-opengl2#changes-needed-to-the-code

2024-08-06 07:27 UTC, ntadej commented
This is still causing a leak in WASM build. As this is not urgent, let me try to find a proper fix.

2024-08-06 15:07 UTC, cgalvan approved these changes

2024-08-06 15:20 UTC, ntadej requested changes
Let me also do a review.

2024-08-13 11:56 UTC, birkskyum commented
> This is still causing a leak in WASM build.

This actually closes a "leak in WASM build" allowing the browser to cancel tile requets.

2024-11-09 18:43 UTC, birkskyum commented
@ntadej , is it okay with you if we merge the fix, so that the code can run, and then investigate the persisting memory leak later on?

2024-11-09 23:18 UTC, louwers approved these changes

2024-11-09 23:22 UTC, louwers commented
@birkskyum Your suggestion sounds reasonable to me. I think @ntadej was afk last month, let's give him a chance to respond this weekend and merge on Monday otherwise.

2024-11-10 10:00 UTC, ntadej commented
Sorry, I did not see that you condition now with WASM. I think it's fine for now until I have time to investigate closer.

Note that I am a bit disappointed in MapLibre memory usage so I plan to investigate eventually if there are not more leaks.

2024-11-10 10:01 UTC, ntadej approved these changes

2024-11-10 10:01 UTC, ntadej commented
Before we merge, is this already in `main`?

2024-11-10 19:48 UTC, louwers commented
No it's not @birkskyum Could you make a new PR that targets main?

2024-11-10 21:47 UTC, josxha commented
It's possible to change the targeted branch of the pull request. 
https://docs.github.com/de/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

2024-11-10 21:51 UTC, louwers commented
@josxha I tried, but then there's a bunch of unrelated changes in the PR...

2025-04-26 08:00 UTC, ntadej commented
Let me get back to this and we can then cherry-pick to the `main` branch.

2025-04-26 18:07 UTC, merged