Toggle tile cache final API
maplibre/maplibre-native pull request #2723
Opened 2024-08-14 20:15 UTC by alexcristici

2024-08-14 20:27 UTC, louwers commented on src/mbgl/renderer/render_orchestrator.hpp
> +    bool getTileCacheEnabled();
Can be const.

2024-08-14 20:29 UTC, louwers reviewed
Looks good, but we should probably have some kind of test coverage for this.

2024-08-16 21:10 UTC, louwers requested changes
Please add a simple test to the C++ unit tests (or modify an existing one) that just toggles it and renders something so we have some coverage. Ideally also for Android and iOS.

2024-08-20 14:31 UTC, TimSylvester approved these changes

2024-08-20 19:20 UTC, louwers approved these changes
Thanks for the smoke tests.

A test that tries to render without the cache enabled would be good at some point.

2024-08-20 21:28 UTC, merged