Expose RENDERMODE_CONTINUOUSLY and RENDERMODE_WHEN_DIRTY
maplibre/maplibre-native pull request #2801
Opened 2024-09-04 22:43 UTC by alasram

To save power, MapLibre only renders the map scene when it becomes dirty (an Android event causes the map to change). This behavior is desired in production. However, when testing performance and particularly trying to automatically detect stuttering, it is better to use continuous rendering.
`GLSurfaceView` already has the ability to switch between `RENDERMODE_CONTINUOUSLY` and `RENDERMODE_WHEN_DIRTY`. This PR simply exposes these option MapLibre client apps.

2024-09-05 19:55 UTC, alasram commented
@louwers CI is failing. Can you tell me what log I should look at to understand the failure?

2024-09-05 20:25 UTC, louwers commented
Hmm the logs should show up if you click through but

```
Test spec output for run 'arn:aws:devicefarm:us-west-2:373521797162:run:20687d72-0e46-403e-8f03-0941850665bc/5146eb99-3855-474d-aa1c-8f132baf221e' not found
```

AWS Device Farm logs can also be found via this guide: https://github.com/maplibre/maplibre-native/wiki/AWS-Device-Farm-Logs

Did you try running the (Android) C++ Unit Tests locally? They are in `test/android`.

2024-09-05 21:40 UTC, alasram commented
@louwers All tests are passing on my phone. The runner hangs at the end but this is true on main as well. It shows this log without returning:
```
2024-09-05 14:36:42.267 11218-11255 GTest                   org.maplibre.cpp_test_runner         I  Test program ended with 955 tests run.
2024-09-05 14:36:42.267 11218-11255 mbgl                    org.maplibre.cpp_test_runner         I  {Thread-139}[General]: TestRunner finished with status: '0'
2024-09-05 14:36:42.268 11218-11247 mbgl                    org.maplibre.cpp_test_runner         I  {Thread-2}[General]: TestRunner done
```

2024-09-12 14:45 UTC, mwilsnd approved these changes

2024-09-12 20:04 UTC, louwers requested changes
How do users know when the view is ready for this method to be called?

I don't really like this API. If I understand it correctly, it is OpenGL specific. Taking an `int` (instead of some kind of `enum class`) is acceptable for internal API but not so much for a public API. And if we want people to configure low level rendering, we should expose that on some low level object, otherwise the MapView will turn into a kitchen sink.

2024-09-13 23:00 UTC, alasram commented
@louwers You're right that exposing it as-is to client apps without a proper enum is wrong. I fixed this. It should work in both Vulkan and GL. It won't work for TextureView which seems to be a deprecated feature.

2024-09-16 11:27 UTC, louwers requested changes
Thanks for adding the enum.

I have one more request, we should add some test coverage. At the minimum just toggling the rendering refresh mode similar to: https://github.com/alexcristici/maplibre-native/blob/f74f4ff3cf3983a07cbd25391103d8f2950846d5/platform/android/MapLibreAndroidTestApp/src/androidTest/java/org/maplibre/android/maps/MapLibreMapTest.kt#L471-L481

2024-09-17 00:38 UTC, louwers approved these changes

2024-09-17 19:59 UTC, merged