Fix MapSnapshotter
maplibre/maplibre-native pull request #2967
Opened 2024-10-25 17:42 UTC by Zverik

Hopefully fixed #2869.

Frankly I'm not an Android developer, but a proper developer from our company says this line fixes things. He says, "NPE was because before the icon was png, but now it's svg, and you load those differently".

2024-10-26 13:17 UTC, louwers requested changes
For me the 'Snapshot Activity' part of the test app works fine before, but when I try out this PR I get:

> Failed to create image decoder with message 'unimplemented'

What exactly is broken?

2024-10-29 07:53 UTC, Zverik commented
Okay I think we need more MS tests...

2024-10-29 12:10 UTC, louwers approved these changes

2024-10-29 12:10 UTC, louwers commented
I agree...

2024-10-29 12:10 UTC, merged