Add windows support to MBTiles file source
maplibre/maplibre-native pull request #905
Opened 2023-03-16 04:52 UTC by tdcosta100

MBTiles file source requires absolute URIs using the scheme `mbtiles://`. In Linux it works with something like `mbtiles:///home/user/map/tiles.mbtiles`, but in Windows it would be something like `mbtiles:///C:/Users/user/map/tiles.mbtiles` (local files) or `mbtiles:////computer/share/map/tiles.mbtiles` (UNC paths), but it does not work, because the path does not start with a slash. This PR aims to correct this situation allowing validation of Windows absolute paths.

2023-03-16 12:03 UTC, louwers requested changes
Please extract this logic in a function in `platform/default` which is overriden in `platform/windows` similarly as for other platform-specific implementations.

Edit: I looked into the Windows PR now and I realize quite a few platform-specific `#define` statements were included with that as well. As I see it we should avoid this as much as possible going forward and keep the core as platform-agnostic as possible.

2023-03-16 15:07 UTC, tdcosta100 commented
Okay, I can make a `mbtiles_file_source.cpp` for Windows. It's a little overkill, since my only change is the validation of the URL, the rest of the code will remain untouched. But like you said, doing this will allow it to be platform-agnostic.

2023-03-16 17:10 UTC, tdcosta100 commented
I think yes, the code can be reworked to extract this as a function. Something like `is_absolute_uri(const std::string&)`.

It checks against the resource URL to guarantee the path to the .mbtiles file is absolute. For example, in the URI `mbtiles:///home/user/tiles.mbtiles`, the part of the path is `/home/user/tiles.mbtiles`. This is an absolute path. In other hand, the URI `mbtiles://user/tiles.mbtiles` have the path `user/tiles.mbtiles`, that is, a relative path. Checking against `:///` ensures the path starts with `/`, so it's an absolute path.

In Windows, absolute paths must have a drive letter (C:, D:, X:, etc), or be UNC paths (starting with `\\` or `//`). So we cannot check against `:///`, because we must accept something like `mbtiles://C:/Users/user/tiles.mbtiles`.

2023-03-16 23:34 UTC, louwers commented
That sounds good!

2023-03-17 00:10 UTC, tdcosta100 commented
The only problem is: even if we extract a function to check if the URI contains an absolute path, where can I override it in Windows platform? This class doesn't have a `Impl` internal class, unfortunately. But for sure extracting this as a method is the best way, I will commit this change.

2023-03-17 01:11 UTC, tdcosta100 commented
Okay, forget what I said. It has a `Impl` class, so I can customize it.

2023-03-17 01:34 UTC, tdcosta100 commented
So I moved this piece of code to an external function. But how to implement it in Windows? Should I keep it as a prototype, then I implement it in every platform? I need guidance in this refactor.

2023-03-17 18:49 UTC, tdcosta100 commented
I think we could use `[std::filesystem::path::is_absolute()](https://en.cppreference.com/w/cpp/filesystem/path/is_absrel)`, but only if we use C++17. Is this our case?

2023-03-17 18:49 UTC, louwers commented
> I think we could use `[std::filesystem::path::is_absolute()](https://en.cppreference.com/w/cpp/filesystem/path/is_absrel)`, but only if we use C++17. Is this our case?

Yes it is!

2023-03-17 18:53 UTC, tdcosta100 commented
Nice. This is already a platform-indepent way to do things, so it will be a nice approach.

2023-03-17 19:02 UTC, louwers commented
> Nice. This is already a platform-indepent way to do things, so it will be a nice approach.

Neat. Let's use it then.

2023-03-17 19:11 UTC, tdcosta100 commented
Done, hope the tests will pass. I think it's even nicer than before.

2023-03-17 19:39 UTC, tdcosta100 commented
Oh no, apparently C++17 is not fully supported in MacOS builds, unless you put a `-std=c++17` switch when configuring. I will investigate further and do a separate PR to test the workflows with this option.

2023-03-17 20:24 UTC, louwers commented
> Oh no, apparently C++17 is not fully supported in MacOS builds, unless you put a `-std=c++17` switch when configuring. I will investigate further and do a separate PR to test the workflows with this option.

Let me fix that.

2023-03-17 20:25 UTC, tdcosta100 commented
Thanks! I'm really trying where to change that, but I don't have the knowledge to do that yet.

2023-03-17 20:49 UTC, louwers commented
> Thanks! I'm really trying where to change that, but I don't have the knowledge to do that yet.

We are already compiling with the C++17 flag, but this particular function has only been implemented on macOS 10.15 and iOS 13.0.

Since we want to support iOS 12.0 for the time being, I suggest the following mitigation:

```
// remove the following #ifdef once iOS 13.0+ is set as deployment target
// https://github.com/maplibre/maplibre-gl-native/pull/905
#ifdef __APPLE__
old if statement
#elif
new if statement
#endif
```

This is acceptable in my eyes because it is temporary.

2023-03-17 20:52 UTC, tdcosta100 commented
Okay, I can do that.

2023-03-17 21:09 UTC, louwers commented
I *think* the header is available even though the functions aren't.

2023-03-17 21:11 UTC, tdcosta100 commented
Nice, it will make the code cleaner.

2023-03-17 22:23 UTC, louwers commented
Is it OK if we await the result of the following discussion?

https://github.com/maplibre/maplibre-gl-native/discussions/915

2023-03-17 23:21 UTC, tdcosta100 commented
Yes, I think is good to wait for the #915 discussion. If it doesn't last too much, of course hahaha.

2023-03-18 00:27 UTC, tdcosta100 commented
It's a reasonable time, but I just remembered I can skip QT as well, so I will keep it out of this change (using the `__QT__` define check).

2023-03-18 02:23 UTC, tdcosta100 commented
Yay, everything passed. I also tested skip just Qt 5 and allow this change on Qt 6, but a lot of errors succeeded, so I will keep it only in other platforms (except, of course, Apple).

2023-03-18 10:45 UTC, louwers commented
> Yay, everything passed. I also tested skip just Qt 5 and allow this change on Qt 6, but a lot of errors succeeded, so I will keep it only in other platforms (except, of course, Apple).

OK, but I assume an MBTiles file source on Qt + Windows will not work then?

2023-03-19 00:55 UTC, tdcosta100 commented
> > Yay, everything passed. I also tested skip just Qt 5 and allow this change on Qt 6, but a lot of errors succeeded, so I will keep it only in other platforms (except, of course, Apple).
> 
> OK, but I assume an MBTiles file source on Qt + Windows will not work then? Do you know which Qt build was giving errors?
> 
> One more annoying question: can we add a test?

At most, it will work as always have been since it was implemented, I don't know how it was working before. You can see the failed workflow [here](https://github.com/maplibre/maplibre-gl-native/actions/runs/4452955656/jobs/7821074283). The most strange part is: it has the `-std=c++17` switch, but apparently this is not enough. Maybe it is using an outdated compiler, something like that. But it needs further investigation, I can try to reproduce it in my computer, if I know how to download Qt without installing it. I think I can do that, just need to try it.

Regarding the test: if it doesn't exist yet, we can add one, I just need to understand where these test types are.

2023-03-21 07:19 UTC, tdcosta100 commented
Okay, so I studied the Qt buildsystem a little more, and managed to enable `#include <filesystem>` in Qt >= 6.2.2 (which is the first version you can use MinGW >= 9.1.0, versions below that doesn't support `filesystem` well).

But this doesn't mean you cannot use absolute paths in Windows in versions below 6.2.2. You can use [DOS device paths](https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#dos-device-paths) to achieve that. They work ok, you just need to use forward slashes (`//`) instead backslashes (`\\`). I tested with Qt 5.15.2 and Qt 6.4.2, and both worked (6.4.2 allows using standard Windows absolute paths, in addition to DOS device paths)

2023-03-21 07:39 UTC, tdcosta100 commented
Added a use to `std::filesystem::temp_directory_path()` in Qt test app, since it defines the temporary database path as a hardcoded path. This will be future-proof, since it leaves to the platform implementation to decide where the temporary directory is.

2023-04-04 22:29 UTC, tdcosta100 commented
@louwers, I think it's better now. I dropped the changes for the Qt test app, since I'm not touching Qt anymore.

2023-04-17 08:41 UTC, louwers requested changes
@tdcosta100 Duplicated code is a no go in my book. My idea was to just create a new file for just this (maybe platform specific) is absolute path function, sorry if I was being unclear. If it works for you we can schedule a 30 minute call and get this sorted: https://calendly.com/bart-louwers/30min

2023-04-19 00:39 UTC, tdcosta100 commented
I think we can think how to rework `MBTilesFileSource` class. Maybe I can contact you in Slack? I think it's better to communicate with.

2023-04-21 22:02 UTC, tdcosta100 commented
@louwers, please check if doing this way makes it better. I can, of course, move the entire `#if defined(USE_STD_FILESYSTEM)` to the Windows section, if you think it's better. `std::filesystem::path` will become more available in other systems when upgrading the minimum platform versions.

2023-04-22 16:55 UTC, ntadej commented
Which platform is missing `std::filesystem`? This should be part of C++17.

2023-04-22 17:31 UTC, tdcosta100 commented
@ntadej, unfortunately even with C++17, some build systems fail: [MacOS, old buid but same error](https://github.com/maplibre/maplibre-gl-native/actions/runs/4451303053/jobs/7817798284), [iOS](https://github.com/maplibre/maplibre-gl-native/actions/runs/4768658715/jobs/8478219496) and [MinGW 8.1.0 (Qt 5)](https://github.com/maplibre/maplibre-gl-native/actions/runs/4768658720/jobs/8478221471).

2023-04-22 17:34 UTC, ntadej commented
Thanks for clarification. Your implementation makes sense.

2023-04-22 17:36 UTC, ntadej approved these changes

2023-04-22 17:40 UTC, tdcosta100 commented
When in the future minimum supported versions increase, we can use `std::filesystem::path::is_absolute()` for everyone. Maybe in 1 year or 2.

2023-06-26 09:56 UTC, louwers approved these changes

2023-06-26 09:57 UTC, merged

2023-08-20 06:58 UTC, donno commented
Is the syntax suppose to be: 
`mbtiles:///C:/Users/user/map/tiles.mbtiles`
or 
`mbtiles://C:/Users/user/map/tiles.mbtiles`

The original comment here suggests the former, however the merged code change suggests the latter  because it looks for :// then passes the resulting path to essentially `std::filesystem::path(path).is_absolute();`. which won't return true if there is a / at the start of the path as it will expect it to start with a drive letter not a slash. A UNC style path with \\ or // will be considered absolute.

Perhaps the correct form could be added to the README.md for Windows.

2023-08-20 09:12 UTC, tdcosta100 commented
The original comment suggests a way that not touches the original check, hence the first syntax. But the idea evolved since then, so the check was changed and now it accepts non-slash absolute paths (mandatory in Windows). A more recent comment about this is the one below:

> I think yes, the code can be reworked to extract this as a function. Something like `is_absolute_uri(const std::string&)`.
> 
> It checks against the resource URL to guarantee the path to the .mbtiles file is absolute. For example, in the URI `mbtiles:///home/user/tiles.mbtiles`, the part of the path is `/home/user/tiles.mbtiles`. This is an absolute path. In other hand, the URI `mbtiles://user/tiles.mbtiles` have the path `user/tiles.mbtiles`, that is, a relative path, so it does not accept this URI. Checking against `:///` ensures the path starts with `/`, so it's an absolute path.
> 
> In Windows, absolute paths must have a drive letter (C:, D:, X:, etc), or be UNC paths (starting with `\\` or `//`). So we cannot check against `:///`, because we must accept something like `mbtiles://C:/Users/user/tiles.mbtiles`.

You are right, a tip on `mbtiles://` URL syntax can be added in README.md for Windows.